FileGetAttrib(aFilespec){
	static FILE_ATTRIBUTE_READONLY:=1,FILE_ATTRIBUTE_ARCHIVE:=32,FILE_ATTRIBUTE_SYSTEM:=4,FILE_ATTRIBUTE_HIDDEN:=2,FILE_ATTRIBUTE_NORMAL:=128
				,FILE_ATTRIBUTE_DIRECTORY:=16,FILE_ATTRIBUTE_OFFLINE:=4096,FILE_ATTRIBUTE_COMPRESSED:=2048,FILE_ATTRIBUTE_TEMPORARY:=256
	if (0xFFFFFFFF = attr := DllCall("GetFileAttributes","Str",aFilespec=""?A_LoopFileFullPath:aFileSpec)){ ; Failure, probably because file doesn't exist.
    ErrorLevel:=1
		return
  }
  ErrorLevel:=0
	return (attr&FILE_ATTRIBUTE_READONLY?"R":"") (attr&FILE_ATTRIBUTE_ARCHIVE?"A":"") (attr&FILE_ATTRIBUTE_SYSTEM?"S":"") 
			.  (attr&FILE_ATTRIBUTE_HIDDEN?"H":"") (attr&FILE_ATTRIBUTE_NORMAL?"N":"") (attr&FILE_ATTRIBUTE_DIRECTORY?"D":"")
			.  (attr&FILE_ATTRIBUTE_OFFLINE?"O":"") (attr&FILE_ATTRIBUTE_COMPRESSED?"C":"") (attr&FILE_ATTRIBUTE_TEMPORARY?"T":"")
}
