import "wtypes.idl";

[
    uuid(A9863C65-8CD4-4069-893D-3B5A3DDFAE88),
    version(1.0)
]
library LibCOMServer
{
	importlib("stdole32.tlb");
	importlib("stdole.tlb"); 

	[ uuid(04FFE41B-8FE9-4479-990A-B186EC73F49C),
	  dual,
	  oleautomation 
	]
	interface ICOMServer : IDispatch
	{
		[id(1)] HRESULT Name([out, retval] BSTR* objectname);
		[id(2)] HRESULT ahktextdll([in,optional] VARIANT script,[in,optional] VARIANT options,[in,optional] VARIANT params, [out, retval] unsigned int* hThread);
		[id(3)] HRESULT ahkdll([in,optional] VARIANT filepath,[in,optional] VARIANT options,[in,optional] VARIANT params, [out, retval] unsigned int* hThread);
		[id(4)] HRESULT ahkPause([in,optional] VARIANT aChangeTo,[out, retval] BOOL* paused);
		[id(5)] HRESULT ahkReady([out, retval] BOOL* ready);
		[id(6)] HRESULT ahkFindLabel([in] VARIANT aLabelName,[out, retval] unsigned int* pLabel);
		[id(7)] HRESULT ahkgetvar([in] VARIANT name,[in,optional] VARIANT getVar,[out, retval] BSTR* returnVal);
		[id(8)] HRESULT ahkassign([in] VARIANT name,[in,optional] VARIANT value,[out, retval] unsigned int* success);
		[id(9)] HRESULT ahkExecuteLine([in,optional] VARIANT line,[in,optional] VARIANT aMode,[in,optional] VARIANT wait,[out, retval] unsigned int* pLine);
		[id(10)] HRESULT ahkLabel([in] VARIANT aLabelName,[in,optional] VARIANT nowait,[out, retval] BOOL* success);
		[id(11)] HRESULT ahkFindFunction([in] VARIANT FuncName,[out, retval] unsigned int* pFunc);
		[id(12)] HRESULT ahkFunction([in] VARIANT FuncName,[in,optional] VARIANT param1,[in,optional] VARIANT param2,[in,optional] VARIANT param3,[in,optional] VARIANT param4,[in,optional] VARIANT param5,[in,optional] VARIANT param6,[in,optional] VARIANT param7,[in,optional] VARIANT param8,[in,optional] VARIANT param9,[in,optional] VARIANT param10,[out, retval] BSTR* returnVal);
		[id(13)] HRESULT ahkPostFunction([in] VARIANT FuncName,[in,optional] VARIANT param1,[in,optional] VARIANT param2,[in,optional] VARIANT param3,[in,optional] VARIANT param4,[in,optional] VARIANT param5,[in,optional] VARIANT param6,[in,optional] VARIANT param7,[in,optional] VARIANT param8,[in,optional] VARIANT param9,[in,optional] VARIANT param10,[out, retval] unsigned int* returnVal);
		[id(14)] HRESULT ahkKey([in] VARIANT name,[out, retval] BOOL* success);
		[id(15)] HRESULT addScript([in] VARIANT script,[in,optional] VARIANT replace,[out, retval] unsigned int* success);
		[id(16)] HRESULT addFile([in] VARIANT filepath,[in,optional] VARIANT aAllowDuplicateInclude,[in,optional] VARIANT aIgnoreLoadFailure,[out, retval] unsigned int* success);
		[id(17)] HRESULT ahkExec([in] VARIANT script,[out, retval] BOOL* success);
		[id(18)] HRESULT ahkTerminate([in,optional] VARIANT kill,[out, retval] BOOL* success);
		
	}

	[ uuid(C00BCC8C-5A04-4392-870F-20AAE1B926B2),
	  helpstring("AutoHotkey Script") 
	]
	coclass CoCOMServer
	{
		[default] interface ICOMServer;
	}
}
